language: generic
sudo: false

env:
  BYOND_MAJOR="509"
  BYOND_MINOR="1318"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

before_script:
  - ./install_byond.sh
  - scripts/dm.sh -DTESTING dmut.dme
