language: generic
sudo: false

env:
  BYOND_MAJOR="509"
  BYOND_MINOR="1318"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - ./install-byond.sh

script:
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - scripts/dm.sh -DTESTING dmut.dme

  - DreamDaemon dmut.dmb 2>&1 | tee dmut.log
  - grep '## DMUT: RESULT: PASSING' dmut.log
